name: Date Extractor Workflow

on:
  push:
    branches:
      - main  # Trigger workflow when code is pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python 3.x
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run the unit tests
    - name: Run unit tests
      run: |
        python -m unittest discover

    # Step 5: Check for specific commit comment
    - name: Check for specific commit comment
      run: |
        git log -1 --pretty=%B | grep "Live quiz complete"
      continue-on-error: false